
import Contextnav from "@/context/cnav";
import "./globals.css";
import { Toaster } from './(components)/ui/toaster';
import  Login  from "./(components)/login";

import ViewProvider from "@/app/(components)/context/navs";
   

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"></link>
      <body className="">
      <Contextnav >
    <ViewProvider>
    
        <Login>
        {children}
        </Login>
        <Toaster />

    </ViewProvider>

     </Contextnav>

        </body>
    </html>  
  );
}
